🚧Create release workflow
KinsonDigital/BranchValidator pull request #100
Opened 2023-05-01 10:26 UTC by kselena

<h1 style="font-weight:bold" align="center">Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: feature/<issue-num>-<description>
      Example: feature/123-my-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_development_** branch with the name **_develop_**.

- [ ] The **_base(target)_** branch for this pull request is a **_development_** branch with the name **_develop_**.
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

💡For more information on branching, refer to the project's [branching documentation](https://github.com/KinsonDigital/.github/blob/master/docs/BranchingFullGitFlow.md).

- [ ] The associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] The pull request title matches the title of the associated issue.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] The assigned project matches the project of the associated issue.

- [ ] The assigned milestone matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_develop_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2023-05-02 11:41 UTC, kselena commented
> **Note** PR and issue put on https://github.com/KinsonDigital/BranchValidator/labels/on%20hold
> Reason: Waiting for the cicd scripts to be added to the org repo and to update the release workflow

2023-05-12 06:42 UTC, KinsonDigitalAdmin requested changes

2023-05-12 06:42 UTC, KinsonDigitalAdmin commented on .github/workflows/release.yml
> +      run: deno run --allow-run "${{ github.workspace }}/.github/cicd/validate-tag.ts" "${{ inputs.release_type }}" "v${{ steps.get-version.outputs.version }}";
Update the script path to a URL to the script in the infrastructure repository.
This is currently on hold to verify that it works with package monster.  

> **Warning** Do not update this until we have proven the concept with PackageMonster first.

2023-05-12 06:42 UTC, KinsonDigitalAdmin commented on .github/workflows/release.yml
> +      run: deno run --allow-read "${{ github.workspace }}/.github/cicd/validate-notes.ts" "${{ inputs.release_type }}" "v${{ steps.get-version.outputs.version }}";
Update the script path to a URL to the script in the infrastructure repository.
This is currently on hold to verify that it works with package monster.  

> **Warning** Do not update this until we have proven the concept with PackageMonster first.

2023-05-12 06:45 UTC, KinsonDigitalAdmin requested changes
Update the release workflow to use infrastructure scripts.

> **Warning** Do not do this until we have proven the concept with PackageMonster and the issue has been lifted out of https://github.com/KinsonDigital/BranchValidator/labels/on%20hold status

2023-05-12 12:31 UTC, KinsonDigitalAdmin requested changes

2023-05-12 12:31 UTC, KinsonDigitalAdmin commented on .github/workflows/release.yml
> +        }
This change was not done but the 👍🏻 emoji is there.  
Did you forget to push up the changes?

2023-05-13 11:50 UTC, KinsonDigitalAdmin commented
> **Note** Taken off of https://github.com/KinsonDigital/BranchValidator/labels/on%20hold status.  Concept with org level deno scripts works perfectly.

2023-05-13 11:52 UTC, KinsonDigitalAdmin requested changes

2023-05-13 11:52 UTC, KinsonDigitalAdmin commented on .github/workflows/release.yml
> +      run: deno run --allow-read "${{ github.workspace }}/.github/cicd/validate-notes.ts" "${{ inputs.release_type }}" "v${{ steps.get-version.outputs.version }}";
1. Update the script paths for both steps to a URL to the script in the infrastructure repository.
This is currently on hold to verify that it works with package monster.  
Tasks added to issue.
2. Update to multi-line shell scripts

> **Warning** Do not update this until we have proven the concept with PackageMonster first and the issue has been lifted out of https://github.com/KinsonDigital/BranchValidator/labels/on%20hold status

2023-05-14 13:18 UTC, KinsonDigitalAdmin approved these changes

2023-05-14 13:20 UTC, merged