Release To Preview
KinsonDigital/BranchValidator pull request #45
Opened 2022-08-26 18:12 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Release Pull Request</h1>
<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

- [ ] The **_base(target)_** branch for this pull request is a **_release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: release/v<major>.<minor>.<patch>
      Example: release/v1.2.3
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_release_** branch with the correct naming syntax in the following example.
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: release/v<major>.<minor>.<patch>
    Example: release/v1.2.3
    ```
  </details>

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the example below, using the correct version.
  <details closed><summary>Example</summary>
    
    ``` xml
    Syntax: 🚀Release To Preview - v<major>.<minor>.<patch>-preview.<prev-num>
    Example: 🚀Release To Preview - v1.2.3-preview.4
    ```
  </details>

- [ ] A https://github.com/KinsonDigital/BranchValidator/labels/%F0%9F%9A%80Preview%20Release label has been added to this PR.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] A QA issue has been created and manual QA testing has been performed for the changes being released.

2022-08-26 18:13 UTC, CalvinWilkinson commented
No QA testing required and also not setup

2022-08-26 18:23 UTC, KinsonDigitalAdmin approved these changes, later dismissed

2022-08-27 08:12 UTC, kselena requested changes

2022-08-27 08:12 UTC, kselena commented on Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
> +4. [#9](https://github.com/KinsonDigital/BranchValidator/issues/9) - Updated the name of the GitHub action from `BranchValidator` to `Branch Validator`
Re-number items.  There are two "4's"

2022-08-27 08:12 UTC, kselena commented on Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
> +    - Added a note explaining wny the action must be ran in Ubuntu with some links to some GitHub documentation resources.
spelling/grammar
```suggestion
    - Added a note explaining why the action must run in Ubuntu with some links to some GitHub documentation resources.
```

2022-08-27 08:12 UTC, kselena commented on Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
> +10. [#41](https://github.com/KinsonDigital/BranchValidator/issues/41) - Made various improvements to the pull request templates by adding 2 new tasks as well as rearranging the order of of the tasks.
Remove the extra "of" and added "s" to template.
```suggestion
10. [#41](https://github.com/KinsonDigital/BranchValidator/issues/41) - Made various improvements to the pull request templates by adding 2 new tasks as well as rearranging the order of the tasks.  List of pull request templates updated below:
```

2022-08-27 08:12 UTC, kselena commented on Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
> +    - Create light and dark mode versions of the project logo.
Grammar - updated to use past tense on both 'create' words.
```suggestion
1. [#5](https://github.com/KinsonDigital/BranchValidator/issues/5) - Created logo for project.
    - Created light and dark mode versions of the project logo.
```

2022-08-27 08:12 UTC, kselena commented on Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.2.md
> +9. [#38](https://github.com/KinsonDigital/BranchValidator/issues/38) - Improve project README.
grammar - use past tense
```suggestion
9. [#38](https://github.com/KinsonDigital/BranchValidator/issues/38) - Improved project README.
```

2022-08-27 08:21 UTC, kselena approved these changes

2022-08-27 08:22 UTC, KinsonDigitalAdmin approved these changes

2022-08-27 08:23 UTC, merged